#配置日志
logging:
  config: classpath:log4j2.xml
#配置tomcat
server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
    max-connections: 1000
    #队列长度
    accept-count: 1000
    connection-timeout: 30000
    servlet:
      session:
        timeout:
    threads:
      #最大线程数
      max: 150
      #最小线程数
      min-spare: 3
  servlet:
    register-default-servlet: true

spring:
  #配置数据库
  datasource:
    url: jdbc:mysql://localhost:3306/personal_assistant?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #最小空闲连接数量
      minimum-idle: 5
      #连接池最大连接数
      maximum-pool-size: 10
      #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      #空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 120000
      #数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  #驼峰的json转换配置
  jackson:
    property-naming-strategy: SNAKE_CASE

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml

#swagger配置
swagger:
  enabled: true